/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Pantallas.Indicaciones.*;
import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class SeleccionarAvanzado extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarPrincipiante
     */
    public SeleccionarAvanzado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnCuerpo = new javax.swing.JButton();
        jbtnDialogo = new javax.swing.JButton();
        jbtnSufijo = new javax.swing.JButton();
        jbtnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/humanbody.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sufijo.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 80, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dialogo1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 102));

        jbtnCuerpo.setBackground(new java.awt.Color(252, 59, 30));
        jbtnCuerpo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCuerpo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCuerpo.setText("Partes del cuerpo");
        jbtnCuerpo.setBorder(null);
        jbtnCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuerpoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 286, 75));

        jbtnDialogo.setBackground(new java.awt.Color(252, 59, 30));
        jbtnDialogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDialogo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDialogo.setText("Diálogos");
        jbtnDialogo.setBorder(null);
        jbtnDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDialogoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 89, 286, 75));

        jbtnSufijo.setBackground(new java.awt.Color(252, 59, 30));
        jbtnSufijo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSufijo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSufijo.setText("Uso del sufijo");
        jbtnSufijo.setBorder(null);
        jbtnSufijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSufijoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSufijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 89, 286, 75));

        jbtnRegresar.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jbtnRegresar.setText("<-- REGRESAR");
        jbtnRegresar.setBorder(null);
        jbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/kuzco4Peque.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 19, 19));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccionar Leccion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuerpoActionPerformed
    I_Avanzado_PartesCuerpo ejercicio = new I_Avanzado_PartesCuerpo();
    ejercicio.setVisible(true);
    this.dispose();   
    }//GEN-LAST:event_jbtnCuerpoActionPerformed

    private void jbtnDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDialogoActionPerformed
    I_Avanzado_Dialogo ejercicio = new I_Avanzado_Dialogo();
    ejercicio.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jbtnDialogoActionPerformed

    private void jbtnSufijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSufijoActionPerformed
    I_Avanzado_Sufijo ejercicio = new I_Avanzado_Sufijo();
    ejercicio.setVisible(true);
    this.dispose();     
    }//GEN-LAST:event_jbtnSufijoActionPerformed

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        SeleccionarNivel menu = new SeleccionarNivel();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarAvanzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCuerpo;
    private javax.swing.JButton jbtnDialogo;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JButton jbtnSufijo;
    // End of variables declaration//GEN-END:variables
}
